## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

application_types_to_replace = list(counts[counts<725].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1728        1
C4200        1
C2190        1
C1570        1
C2380        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [14]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C2400        6
C4100        6
C1720        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C1256        2
C1246        2
C1267        2
C3200        2
C1234        2
Name: CLASSIFICATION, dtype: int64

In [7]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() <800].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [8]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [9]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dummies_df['IS_SUCCESSFUL'].values
X = dummies_df.drop(['IS_SUCCESSFUL'], axis=1).values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [10]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [11]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, input_dim=len(X_train_scaled[0]), activation='relu'))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=30, input_dim=len(X_train_scaled[0]), activation='relu'))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3440
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,901
Trainable params: 5,901
Non-trainable params: 0
_________________________________________________________________

In [12]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [13]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=150)

Epoch 1/150
678/684 [============================>.] - ETA: 0s - loss: 0.5773 - accuracy: 0.7129WARNING:tensorflow:Callbacks method `on_test_batch_end` is slow compared to the batch time (batch time: 0.0000s vs `on_test_batch_end` time: 0.0010s). Check your callbacks.
684/684 [==============================] - 1s 998us/step - loss: 0.5769 - accuracy: 0.7134 - val_loss: 0.5519 - val_accuracy: 0.7308
Epoch 2/150
684/684 [==============================] - 1s 781us/step - loss: 0.5576 - accuracy: 0.7270 - val_loss: 0.5479 - val_accuracy: 0.7346
Epoch 3/150
684/684 [==============================] - 1s 752us/step - loss: 0.5535 - accuracy: 0.7288 - val_loss: 0.5468 - val_accuracy: 0.7326
Epoch 4/150
684/684 [==============================] - 1s 750us/step - loss: 0.5520 - accuracy: 0.7306 - val_loss: 0.5462 - val_accuracy: 0.7326
Epoch 5/150
684/684 [==============================] - 1s 753us/step - loss: 0.5501 - accuracy: 0.7293 - val_loss: 0.5470 - val_accuracy: 0.7341
Epoch 6/150
684/684 [==============================] - 1s 756us/step - loss: 0.5492 - accuracy: 0.7307 - val_loss: 0.5437 - val_accuracy: 0.7354
Epoch 7/150
684/684 [==============================] - 1s 766us/step - loss: 0.5483 - accuracy: 0.7312 - val_loss: 0.5475 - val_accuracy: 0.7271
Epoch 8/150
684/684 [==============================] - 1s 753us/step - loss: 0.5474 - accuracy: 0.7309 - val_loss: 0.5461 - val_accuracy: 0.7344
Epoch 9/150
684/684 [==============================] - 1s 769us/step - loss: 0.5476 - accuracy: 0.7326 - val_loss: 0.5436 - val_accuracy: 0.7352
Epoch 10/150
684/684 [==============================] - 1s 783us/step - loss: 0.5463 - accuracy: 0.7319 - val_loss: 0.5446 - val_accuracy: 0.7334
Epoch 11/150
684/684 [==============================] - 1s 763us/step - loss: 0.5466 - accuracy: 0.7324 - val_loss: 0.5436 - val_accuracy: 0.7339
Epoch 12/150
684/684 [==============================] - 1s 765us/step - loss: 0.5455 - accuracy: 0.7342 - val_loss: 0.5494 - val_accuracy: 0.7326
Epoch 13/150
684/684 [==============================] - 1s 765us/step - loss: 0.5458 - accuracy: 0.7328 - val_loss: 0.5502 - val_accuracy: 0.7357
Epoch 14/150
684/684 [==============================] - 1s 765us/step - loss: 0.5451 - accuracy: 0.7339 - val_loss: 0.5459 - val_accuracy: 0.7318
Epoch 15/150
684/684 [==============================] - 1s 767us/step - loss: 0.5445 - accuracy: 0.7341 - val_loss: 0.5433 - val_accuracy: 0.7349
Epoch 16/150
684/684 [==============================] - 1s 772us/step - loss: 0.5441 - accuracy: 0.7348 - val_loss: 0.5443 - val_accuracy: 0.7372
Epoch 17/150
684/684 [==============================] - 1s 782us/step - loss: 0.5435 - accuracy: 0.7351 - val_loss: 0.5436 - val_accuracy: 0.7362
Epoch 18/150
684/684 [==============================] - 1s 758us/step - loss: 0.5436 - accuracy: 0.7342 - val_loss: 0.5445 - val_accuracy: 0.7326
Epoch 19/150
684/684 [==============================] - 1s 775us/step - loss: 0.5434 - accuracy: 0.7353 - val_loss: 0.5427 - val_accuracy: 0.7354
Epoch 20/150
684/684 [==============================] - 1s 770us/step - loss: 0.5427 - accuracy: 0.7351 - val_loss: 0.5443 - val_accuracy: 0.7359
Epoch 21/150
684/684 [==============================] - 1s 764us/step - loss: 0.5431 - accuracy: 0.7349 - val_loss: 0.5452 - val_accuracy: 0.7331
Epoch 22/150
684/684 [==============================] - 1s 771us/step - loss: 0.5424 - accuracy: 0.7351 - val_loss: 0.5441 - val_accuracy: 0.7310
Epoch 23/150
684/684 [==============================] - 1s 769us/step - loss: 0.5422 - accuracy: 0.7340 - val_loss: 0.5448 - val_accuracy: 0.7339
Epoch 24/150
684/684 [==============================] - 1s 787us/step - loss: 0.5423 - accuracy: 0.7352 - val_loss: 0.5434 - val_accuracy: 0.7359
Epoch 25/150
684/684 [==============================] - 1s 770us/step - loss: 0.5419 - accuracy: 0.7357 - val_loss: 0.5431 - val_accuracy: 0.7326
Epoch 26/150
684/684 [==============================] - 1s 800us/step - loss: 0.5421 - accuracy: 0.7360 - val_loss: 0.5454 - val_accuracy: 0.7344
Epoch 27/150
684/684 [==============================] - 1s 776us/step - loss: 0.5417 - accuracy: 0.7362 - val_loss: 0.5446 - val_accuracy: 0.7367
Epoch 28/150
684/684 [==============================] - 1s 788us/step - loss: 0.5410 - accuracy: 0.7373 - val_loss: 0.5443 - val_accuracy: 0.7302
Epoch 29/150
684/684 [==============================] - 1s 788us/step - loss: 0.5412 - accuracy: 0.7368 - val_loss: 0.5442 - val_accuracy: 0.7362
Epoch 30/150
684/684 [==============================] - 1s 821us/step - loss: 0.5412 - accuracy: 0.7364 - val_loss: 0.5444 - val_accuracy: 0.7349
Epoch 31/150
684/684 [==============================] - 1s 798us/step - loss: 0.5406 - accuracy: 0.7354 - val_loss: 0.5423 - val_accuracy: 0.7354
Epoch 32/150
684/684 [==============================] - 1s 768us/step - loss: 0.5413 - accuracy: 0.7359 - val_loss: 0.5462 - val_accuracy: 0.7334
Epoch 33/150
684/684 [==============================] - 1s 771us/step - loss: 0.5407 - accuracy: 0.7362 - val_loss: 0.5437 - val_accuracy: 0.7370
Epoch 34/150
684/684 [==============================] - 1s 772us/step - loss: 0.5402 - accuracy: 0.7371 - val_loss: 0.5460 - val_accuracy: 0.7344
Epoch 35/150
684/684 [==============================] - 1s 764us/step - loss: 0.5404 - accuracy: 0.7360 - val_loss: 0.5439 - val_accuracy: 0.7341
Epoch 36/150
684/684 [==============================] - 1s 752us/step - loss: 0.5403 - accuracy: 0.7373 - val_loss: 0.5446 - val_accuracy: 0.7344
Epoch 37/150
684/684 [==============================] - 1s 747us/step - loss: 0.5400 - accuracy: 0.7364 - val_loss: 0.5462 - val_accuracy: 0.7334
Epoch 38/150
684/684 [==============================] - 1s 750us/step - loss: 0.5401 - accuracy: 0.7367 - val_loss: 0.5454 - val_accuracy: 0.7336
Epoch 39/150
684/684 [==============================] - 1s 754us/step - loss: 0.5398 - accuracy: 0.7371 - val_loss: 0.5446 - val_accuracy: 0.7352
Epoch 40/150
684/684 [==============================] - 1s 786us/step - loss: 0.5398 - accuracy: 0.7382 - val_loss: 0.5458 - val_accuracy: 0.7344
Epoch 41/150
684/684 [==============================] - 1s 767us/step - loss: 0.5397 - accuracy: 0.7371 - val_loss: 0.5443 - val_accuracy: 0.7354
Epoch 42/150
684/684 [==============================] - 1s 767us/step - loss: 0.5396 - accuracy: 0.7369 - val_loss: 0.5482 - val_accuracy: 0.7341
Epoch 43/150
684/684 [==============================] - 1s 775us/step - loss: 0.5392 - accuracy: 0.7384 - val_loss: 0.5468 - val_accuracy: 0.7367
Epoch 44/150
684/684 [==============================] - 1s 768us/step - loss: 0.5391 - accuracy: 0.7378 - val_loss: 0.5463 - val_accuracy: 0.7313
Epoch 45/150
684/684 [==============================] - 1s 774us/step - loss: 0.5394 - accuracy: 0.7370 - val_loss: 0.5473 - val_accuracy: 0.7352
Epoch 46/150
684/684 [==============================] - 1s 761us/step - loss: 0.5391 - accuracy: 0.7380 - val_loss: 0.5477 - val_accuracy: 0.7341
Epoch 47/150
684/684 [==============================] - 1s 767us/step - loss: 0.5394 - accuracy: 0.7379 - val_loss: 0.5475 - val_accuracy: 0.7344
Epoch 48/150
684/684 [==============================] - 1s 776us/step - loss: 0.5387 - accuracy: 0.7381 - val_loss: 0.5470 - val_accuracy: 0.7334
Epoch 49/150
684/684 [==============================] - 1s 750us/step - loss: 0.5388 - accuracy: 0.7374 - val_loss: 0.5452 - val_accuracy: 0.7344
Epoch 50/150
684/684 [==============================] - 1s 752us/step - loss: 0.5387 - accuracy: 0.7381 - val_loss: 0.5479 - val_accuracy: 0.7331
Epoch 51/150
684/684 [==============================] - 1s 773us/step - loss: 0.5387 - accuracy: 0.7390 - val_loss: 0.5465 - val_accuracy: 0.7341
Epoch 52/150
684/684 [==============================] - 1s 747us/step - loss: 0.5385 - accuracy: 0.7380 - val_loss: 0.5486 - val_accuracy: 0.7256
Epoch 53/150
684/684 [==============================] - 1s 750us/step - loss: 0.5382 - accuracy: 0.7383 - val_loss: 0.5484 - val_accuracy: 0.7357
Epoch 54/150
684/684 [==============================] - 1s 786us/step - loss: 0.5384 - accuracy: 0.7373 - val_loss: 0.5459 - val_accuracy: 0.7341
Epoch 55/150

684/684 [==============================] - 1s 738us/step - loss: 0.5383 - accuracy: 0.7390 - val_loss: 0.5470 - val_accuracy: 0.7339
Epoch 56/150
684/684 [==============================] - 1s 755us/step - loss: 0.5386 - accuracy: 0.7377 - val_loss: 0.5467 - val_accuracy: 0.7336
Epoch 57/150
684/684 [==============================] - 1s 753us/step - loss: 0.5377 - accuracy: 0.7384 - val_loss: 0.5488 - val_accuracy: 0.7359
Epoch 58/150
684/684 [==============================] - 1s 749us/step - loss: 0.5377 - accuracy: 0.7374 - val_loss: 0.5482 - val_accuracy: 0.7336
Epoch 59/150
684/684 [==============================] - 1s 770us/step - loss: 0.5377 - accuracy: 0.7379 - val_loss: 0.5461 - val_accuracy: 0.7336
Epoch 60/150
684/684 [==============================] - 1s 750us/step - loss: 0.5376 - accuracy: 0.7386 - val_loss: 0.5478 - val_accuracy: 0.7323
Epoch 61/150
684/684 [==============================] - 1s 793us/step - loss: 0.5372 - accuracy: 0.7388 - val_loss: 0.5498 - val_accuracy: 0.7339
Epoch 62/150
684/684 [==============================] - 1s 750us/step - loss: 0.5374 - accuracy: 0.7380 - val_loss: 0.5516 - val_accuracy: 0.7323
Epoch 63/150
684/684 [==============================] - 1s 764us/step - loss: 0.5375 - accuracy: 0.7378 - val_loss: 0.5471 - val_accuracy: 0.7339
Epoch 64/150
684/684 [==============================] - 1s 748us/step - loss: 0.5374 - accuracy: 0.7376 - val_loss: 0.5472 - val_accuracy: 0.7344
Epoch 65/150
684/684 [==============================] - 1s 764us/step - loss: 0.5372 - accuracy: 0.7383 - val_loss: 0.5505 - val_accuracy: 0.7336
Epoch 66/150
684/684 [==============================] - 1s 746us/step - loss: 0.5371 - accuracy: 0.7377 - val_loss: 0.5525 - val_accuracy: 0.7357
Epoch 67/150
684/684 [==============================] - 1s 774us/step - loss: 0.5370 - accuracy: 0.7382 - val_loss: 0.5496 - val_accuracy: 0.7326
Epoch 68/150
684/684 [==============================] - 1s 766us/step - loss: 0.5368 - accuracy: 0.7385 - val_loss: 0.5511 - val_accuracy: 0.7336
Epoch 69/150
684/684 [==============================] - 1s 761us/step - loss: 0.5368 - accuracy: 0.7383 - val_loss: 0.5487 - val_accuracy: 0.7323
Epoch 70/150
684/684 [==============================] - 1s 767us/step - loss: 0.5365 - accuracy: 0.7375 - val_loss: 0.5489 - val_accuracy: 0.7359
Epoch 71/150
684/684 [==============================] - 1s 773us/step - loss: 0.5362 - accuracy: 0.7378 - val_loss: 0.5577 - val_accuracy: 0.7334
Epoch 72/150
684/684 [==============================] - 1s 763us/step - loss: 0.5369 - accuracy: 0.7389 - val_loss: 0.5502 - val_accuracy: 0.7346
Epoch 73/150
684/684 [==============================] - 1s 790us/step - loss: 0.5363 - accuracy: 0.7386 - val_loss: 0.5495 - val_accuracy: 0.7352
Epoch 74/150
684/684 [==============================] - 1s 793us/step - loss: 0.5367 - accuracy: 0.7391 - val_loss: 0.5511 - val_accuracy: 0.7328
Epoch 75/150
684/684 [==============================] - 1s 786us/step - loss: 0.5363 - accuracy: 0.7388 - val_loss: 0.5480 - val_accuracy: 0.7334
Epoch 76/150
684/684 [==============================] - 1s 794us/step - loss: 0.5362 - accuracy: 0.7391 - val_loss: 0.5507 - val_accuracy: 0.7328
Epoch 77/150
684/684 [==============================] - 1s 773us/step - loss: 0.5362 - accuracy: 0.7385 - val_loss: 0.5501 - val_accuracy: 0.7339
Epoch 78/150
684/684 [==============================] - 1s 764us/step - loss: 0.5362 - accuracy: 0.7397 - val_loss: 0.5534 - val_accuracy: 0.7346
Epoch 79/150
684/684 [==============================] - 1s 788us/step - loss: 0.5363 - accuracy: 0.7394 - val_loss: 0.5509 - val_accuracy: 0.7346
Epoch 80/150
684/684 [==============================] - 1s 764us/step - loss: 0.5358 - accuracy: 0.7384 - val_loss: 0.5531 - val_accuracy: 0.7339
Epoch 81/150
684/684 [==============================] - 1s 801us/step - loss: 0.5361 - accuracy: 0.7389 - val_loss: 0.5506 - val_accuracy: 0.7354
Epoch 82/150
684/684 [==============================] - 1s 805us/step - loss: 0.5357 - accuracy: 0.7399 - val_loss: 0.5510 - val_accuracy: 0.7352
Epoch 83/150
684/684 [==============================] - 1s 773us/step - loss: 0.5363 - accuracy: 0.7386 - val_loss: 0.5505 - val_accuracy: 0.7349
Epoch 84/150
684/684 [==============================] - 1s 770us/step - loss: 0.5360 - accuracy: 0.7405 - val_loss: 0.5497 - val_accuracy: 0.7341
Epoch 85/150
684/684 [==============================] - 1s 752us/step - loss: 0.5357 - accuracy: 0.7382 - val_loss: 0.5536 - val_accuracy: 0.7336
Epoch 86/150
684/684 [==============================] - 1s 751us/step - loss: 0.5357 - accuracy: 0.7380 - val_loss: 0.5518 - val_accuracy: 0.7336
Epoch 87/150
684/684 [==============================] - 1s 747us/step - loss: 0.5360 - accuracy: 0.7386 - val_loss: 0.5498 - val_accuracy: 0.7334
Epoch 88/150
684/684 [==============================] - 1s 779us/step - loss: 0.5349 - accuracy: 0.7394 - val_loss: 0.5514 - val_accuracy: 0.7323
Epoch 89/150
684/684 [==============================] - 1s 752us/step - loss: 0.5354 - accuracy: 0.7389 - val_loss: 0.5487 - val_accuracy: 0.7352
Epoch 90/150
684/684 [==============================] - 1s 771us/step - loss: 0.5354 - accuracy: 0.7390 - val_loss: 0.5514 - val_accuracy: 0.7334
Epoch 91/150
684/684 [==============================] - 1s 770us/step - loss: 0.5353 - accuracy: 0.7394 - val_loss: 0.5528 - val_accuracy: 0.7326
Epoch 92/150
684/684 [==============================] - 1s 769us/step - loss: 0.5355 - accuracy: 0.7394 - val_loss: 0.5518 - val_accuracy: 0.7344
Epoch 93/150
684/684 [==============================] - 1s 769us/step - loss: 0.5356 - accuracy: 0.7396 - val_loss: 0.5530 - val_accuracy: 0.7341
Epoch 94/150
684/684 [==============================] - 1s 766us/step - loss: 0.5349 - accuracy: 0.7396 - val_loss: 0.5520 - val_accuracy: 0.7365
Epoch 95/150
684/684 [==============================] - 1s 751us/step - loss: 0.5350 - accuracy: 0.7388 - val_loss: 0.5505 - val_accuracy: 0.7352
Epoch 96/150
684/684 [==============================] - 1s 768us/step - loss: 0.5350 - accuracy: 0.7384 - val_loss: 0.5524 - val_accuracy: 0.7352
Epoch 97/150
684/684 [==============================] - 1s 747us/step - loss: 0.5351 - accuracy: 0.7399 - val_loss: 0.5514 - val_accuracy: 0.7344
Epoch 98/150
684/684 [==============================] - 1s 751us/step - loss: 0.5346 - accuracy: 0.7394 - val_loss: 0.5548 - val_accuracy: 0.7344
Epoch 99/150
684/684 [==============================] - 1s 752us/step - loss: 0.5346 - accuracy: 0.7403 - val_loss: 0.5532 - val_accuracy: 0.7352
Epoch 100/150
684/684 [==============================] - 1s 769us/step - loss: 0.5347 - accuracy: 0.7395 - val_loss: 0.5526 - val_accuracy: 0.7354
Epoch 101/150
684/684 [==============================] - 1s 769us/step - loss: 0.5345 - accuracy: 0.7397 - val_loss: 0.5502 - val_accuracy: 0.7354
Epoch 102/150
684/684 [==============================] - 1s 758us/step - loss: 0.5345 - accuracy: 0.7395 - val_loss: 0.5513 - val_accuracy: 0.7344
Epoch 103/150
684/684 [==============================] - 1s 774us/step - loss: 0.5350 - accuracy: 0.7385 - val_loss: 0.5525 - val_accuracy: 0.7341
Epoch 104/150
684/684 [==============================] - 1s 765us/step - loss: 0.5347 - accuracy: 0.7398 - val_loss: 0.5514 - val_accuracy: 0.7328
Epoch 105/150
684/684 [==============================] - 1s 759us/step - loss: 0.5341 - accuracy: 0.7396 - val_loss: 0.5539 - val_accuracy: 0.7326
Epoch 106/150
684/684 [==============================] - 1s 753us/step - loss: 0.5345 - accuracy: 0.7396 - val_loss: 0.5518 - val_accuracy: 0.7336
Epoch 107/150
684/684 [==============================] - 1s 772us/step - loss: 0.5339 - accuracy: 0.7391 - val_loss: 0.5546 - val_accuracy: 0.7339
Epoch 108/150
684/684 [==============================] - 1s 769us/step - loss: 0.5342 - accuracy: 0.7397 - val_loss: 0.5562 - val_accuracy: 0.7349
Epoch 109/150
684/684 [==============================] - 1s 771us/step - loss: 0.5349 - accuracy: 0.7383 - val_loss: 0.5511 - val_accuracy: 0.7341
Epoch 110/150
684/684 [==============================] - 1s 768us/step - loss: 0.5340 - accuracy: 0.7393 - val_loss: 0.5505 - val_accuracy: 0.7341
Epoch 111/150

684/684 [==============================] - 1s 744us/step - loss: 0.5342 - accuracy: 0.7393 - val_loss: 0.5567 - val_accuracy: 0.7331
Epoch 112/150
684/684 [==============================] - 1s 747us/step - loss: 0.5337 - accuracy: 0.7394 - val_loss: 0.5600 - val_accuracy: 0.7341
Epoch 113/150
684/684 [==============================] - 1s 747us/step - loss: 0.5343 - accuracy: 0.7406 - val_loss: 0.5543 - val_accuracy: 0.7344
Epoch 114/150
684/684 [==============================] - 1s 742us/step - loss: 0.5340 - accuracy: 0.7396 - val_loss: 0.5570 - val_accuracy: 0.7341
Epoch 115/150
684/684 [==============================] - 1s 745us/step - loss: 0.5337 - accuracy: 0.7394 - val_loss: 0.5558 - val_accuracy: 0.7344
Epoch 116/150
684/684 [==============================] - 1s 763us/step - loss: 0.5337 - accuracy: 0.7404 - val_loss: 0.5566 - val_accuracy: 0.7315
Epoch 117/150
684/684 [==============================] - 1s 742us/step - loss: 0.5337 - accuracy: 0.7399 - val_loss: 0.5557 - val_accuracy: 0.7341
Epoch 118/150
684/684 [==============================] - 1s 763us/step - loss: 0.5339 - accuracy: 0.7388 - val_loss: 0.5556 - val_accuracy: 0.7331
Epoch 119/150
684/684 [==============================] - 1s 768us/step - loss: 0.5343 - accuracy: 0.7398 - val_loss: 0.5534 - val_accuracy: 0.7354
Epoch 120/150
684/684 [==============================] - 1s 769us/step - loss: 0.5335 - accuracy: 0.7401 - val_loss: 0.5558 - val_accuracy: 0.7339
Epoch 121/150
684/684 [==============================] - 1s 768us/step - loss: 0.5339 - accuracy: 0.7398 - val_loss: 0.5549 - val_accuracy: 0.7349
Epoch 122/150
684/684 [==============================] - 1s 768us/step - loss: 0.5333 - accuracy: 0.7399 - val_loss: 0.5558 - val_accuracy: 0.7339
Epoch 123/150
684/684 [==============================] - 1s 764us/step - loss: 0.5336 - accuracy: 0.7404 - val_loss: 0.5559 - val_accuracy: 0.7334
Epoch 124/150
684/684 [==============================] - 1s 803us/step - loss: 0.5330 - accuracy: 0.7396 - val_loss: 0.5574 - val_accuracy: 0.7339
Epoch 125/150
684/684 [==============================] - 1s 757us/step - loss: 0.5336 - accuracy: 0.7399 - val_loss: 0.5549 - val_accuracy: 0.7341
Epoch 126/150
684/684 [==============================] - 1s 775us/step - loss: 0.5331 - accuracy: 0.7394 - val_loss: 0.5546 - val_accuracy: 0.7328
Epoch 127/150
684/684 [==============================] - 1s 761us/step - loss: 0.5332 - accuracy: 0.7391 - val_loss: 0.5569 - val_accuracy: 0.7341
Epoch 128/150
684/684 [==============================] - 1s 745us/step - loss: 0.5330 - accuracy: 0.7399 - val_loss: 0.5598 - val_accuracy: 0.7354
Epoch 129/150
684/684 [==============================] - 1s 768us/step - loss: 0.5339 - accuracy: 0.7385 - val_loss: 0.5540 - val_accuracy: 0.7341
Epoch 130/150
684/684 [==============================] - 1s 749us/step - loss: 0.5333 - accuracy: 0.7398 - val_loss: 0.5576 - val_accuracy: 0.7346
Epoch 131/150
684/684 [==============================] - 1s 769us/step - loss: 0.5336 - accuracy: 0.7395 - val_loss: 0.5575 - val_accuracy: 0.7331
Epoch 132/150
684/684 [==============================] - 1s 756us/step - loss: 0.5332 - accuracy: 0.7404 - val_loss: 0.5573 - val_accuracy: 0.7331
Epoch 133/150
684/684 [==============================] - 1s 749us/step - loss: 0.5329 - accuracy: 0.7407 - val_loss: 0.5561 - val_accuracy: 0.7346
Epoch 134/150
684/684 [==============================] - 1s 758us/step - loss: 0.5332 - accuracy: 0.7403 - val_loss: 0.5623 - val_accuracy: 0.7339
Epoch 135/150
684/684 [==============================] - 1s 757us/step - loss: 0.5328 - accuracy: 0.7403 - val_loss: 0.5605 - val_accuracy: 0.7341
Epoch 136/150
684/684 [==============================] - 1s 777us/step - loss: 0.5328 - accuracy: 0.7405 - val_loss: 0.5571 - val_accuracy: 0.7346
Epoch 137/150
684/684 [==============================] - 1s 773us/step - loss: 0.5328 - accuracy: 0.7400 - val_loss: 0.5581 - val_accuracy: 0.7331
Epoch 138/150
684/684 [==============================] - 1s 771us/step - loss: 0.5330 - accuracy: 0.7396 - val_loss: 0.5566 - val_accuracy: 0.7346
Epoch 139/150
684/684 [==============================] - 1s 751us/step - loss: 0.5327 - accuracy: 0.7407 - val_loss: 0.5552 - val_accuracy: 0.7346
Epoch 140/150
684/684 [==============================] - 1s 756us/step - loss: 0.5366 - accuracy: 0.7399 - val_loss: 0.5563 - val_accuracy: 0.7341
Epoch 141/150
684/684 [==============================] - 1s 750us/step - loss: 0.5326 - accuracy: 0.7405 - val_loss: 0.5587 - val_accuracy: 0.7323
Epoch 142/150
684/684 [==============================] - 1s 753us/step - loss: 0.5328 - accuracy: 0.7404 - val_loss: 0.5583 - val_accuracy: 0.7334
Epoch 143/150
684/684 [==============================] - 1s 750us/step - loss: 0.5326 - accuracy: 0.7405 - val_loss: 0.5575 - val_accuracy: 0.7354
Epoch 144/150
684/684 [==============================] - 1s 765us/step - loss: 0.5353 - accuracy: 0.7394 - val_loss: 0.5610 - val_accuracy: 0.7336
Epoch 145/150
684/684 [==============================] - 1s 762us/step - loss: 0.5328 - accuracy: 0.7393 - val_loss: 0.5590 - val_accuracy: 0.7328
Epoch 146/150
684/684 [==============================] - 1s 764us/step - loss: 0.5327 - accuracy: 0.7407 - val_loss: 0.5560 - val_accuracy: 0.7313
Epoch 147/150
684/684 [==============================] - 1s 751us/step - loss: 0.5325 - accuracy: 0.7405 - val_loss: 0.5577 - val_accuracy: 0.7357
Epoch 148/150
684/684 [==============================] - 1s 751us/step - loss: 0.5328 - accuracy: 0.7401 - val_loss: 0.5558 - val_accuracy: 0.7334
Epoch 149/150
684/684 [==============================] - 1s 752us/step - loss: 0.5328 - accuracy: 0.7405 - val_loss: 0.5574 - val_accuracy: 0.7341
Epoch 150/150
684/684 [==============================] - 1s 752us/step - loss: 0.5322 - accuracy: 0.7400 - val_loss: 0.5581 - val_accuracy: 0.7331

In [14]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5716 - accuracy: 0.7285
Loss: 0.5715513229370117, Accuracy: 0.7285131216049194

In [15]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('AlphabetSoupCharity1.h5')